### ISSUE TITLE
Relink BRAW Clips within an Event strange behavior.

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#100]
There's some strange anomalies happening. 
When I drag in an event (Day 17) with the BRAW clips already linked and good for use, this toolbox feature gives me all red dots and the directory is already correct.

When I put in an event made using Sync-N-Link (Day 17-Synced) whose BRAW clips are missing (red alert with "No BRAW clips selected"), then refresh and request permissions in the toolbox , the resulting event still doesn't relink my clips.

So far I've had to relink clips manually one by one using the inspector.

**Comment by latenitefilms** [comment]
I'm going to close this issue in favour of #101.
