### ISSUE TITLE
"Add BRAW Toolbox to Proxy Clips within an EVENT" Toolbox produces invalid FCPXML

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#104]
Using v1.0.6 (44) on Mac Book Pro / M2 Max / macOS 13.2.1 / FCP 10.6.5

I am attempting to use the Add BRAW Toolbox to Proxy Clips within an EVENT feature. Once I get the success message from BRAW Toolbox and drag the green event into my library, the event snaps back into place int he BRAW Toolbox window no matter what I do or how many times I try.  

I have the proxies in the same folder as the braw clips. If I didn't I wouldn't have gotten a success message. I granted access to the top level folder for all assets.

![Screenshot 2023-03-28 at 5 39 56 PM](https://user-images.githubusercontent.com/9577806/228398118-63fa56b1-0c0b-474e-8601-3f93127e8edb.png)
![Screenshot 2023-03-28 at 5 38 17 PM](https://user-images.githubusercontent.com/9577806/228398123-ffb61e5b-aca1-42ce-8528-f8012215a8e5.png)
![Screenshot 2023-03-28 at 5 38 10 PM](https://user-images.githubusercontent.com/9577806/228398125-430cdedb-8c39-4a41-9348-86bc31228d73.png)
![Screenshot 2023-03-28 at 5 38 02 PM](https://user-images.githubusercontent.com/9577806/228398127-1c770af8-6796-48d2-b08a-6e37b9eab491.png)

**Comment by latenitefilms** [comment]
My sincerest apologies for the delayed reply - for some reason GitHub decided to stop sending me email notifications for this repo. Sorry!

If Final Cut Pro is not accepting the dropped file, it means there must be something wrong with the FCPXML.

You should be able to find that FCPXML in this folder:

`/Users/YOUR-USER-NAME/Library/Group Containers/A5HDJTY9X5.com.latenitefilms.BRAWToolbox/Library/Application Support/Last MOV to BRAW.fcpxml`

If you try manually dragging that file into Final Cut Pro, it should hopefully give you an error message with clues to what's going on.

**Comment by tangierc** [comment]
I think I posted the file to the direct contact. Let me know if I need to resend.

**Comment by latenitefilms** [comment]
I don't believe I ever got the `Last MOV to BRAW.fcpxml` from you, so if you can re-send that would be great. Thanks!

**Comment by tangierc** [comment]
No problem. I just sent it.

Thanks

**Comment by latenitefilms** [comment]
This is the error I get when trying to import that FCPXML. Will need to do some further digging.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/22286696/233901885-1da56b43-d807-4078-948d-3c4281f2e7e0.png">

**Comment by latenitefilms** [comment]
Can you try create a new event, with a single `.mov` proxy in it. Make sure the `.braw` is in the same folder as the `.mov`.

Before dragging this event to the Toolbox, select the `.mov` in the Browser, then click **Clip > Open Clip**, and apply a Color Board effect to it (actually doesn't matter what the effect is, just an effect that does nothing) - then try again.

**Comment by latenitefilms** [comment]
As the instructions say, the BRAW file needs to be in the SAME folder as the MOV:

![](https://user-images.githubusercontent.com/22286696/235800852-5a0c447f-8db4-4992-9740-15faad765c58.png)

Have a look at this post, and see if that makes more sense:

https://github.com/latenitefilms/BRAWToolbox/issues/124#issuecomment-1532247236

**Comment by tangierc** [comment]
Hi Chris. My braw file that I imported is in the same folder as the proxy version. It’s a proxy as identified by FCP as a proxy video file other than the original, not proxy in the literal sense as any video file that isn’t the original and lower quality than the original due to codec.  It shows this in the video I sent at 1:16. The braw and proxy files are in the same folder.

Here’s a screenshot of the quicktime video I sent with the braw and proxy file. in the same folder, with the file names being the same. 
￼
Tangier

**Comment by latenitefilms** [comment]
I don't think your screenshot came through, but I can see it in your screen recording:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/22286696/235815943-643e9920-dfc0-4c1e-9d04-b4529831dc24.png">

The BRAW file needs to be in the same folder as the **Original** source file.

This is probably where the confusion lies... When we say "proxy", we don't actually mean Final Cut Pro proxies - we just mean a **MOV** as opposed to a **BRAW** file.

The **Optimised/Original**, **Proxy Preferred** and **Proxy Only** are irrelevant in terms of BRAW Toolbox.

**Comment by tangierc** [comment]
Yes, that’s it.  I know the folders may seem backwards. It’s because I already brought in the MOV and FCP would inherently think that’s the original. So I just put the braw and a copy of the original in a proxy folder since FCP won’t allow the original and proxy to reference the same file.

Tangier

**Comment by latenitefilms** [comment]
So to clarify, you've actually imported the MOV in the `proxy` folder into Final Cut Pro?

...and if you follow these steps, it doesn't work on your machine?

https://github.com/latenitefilms/BRAWToolbox/issues/124#issuecomment-1532247236

**Comment by tangierc** [comment]
The mov file in the proxy folder is linked as an actual proxy file in FCP. A duplicate of that file is in the “original” folder. This was the only one imported directly. 
I could delete that original folder and solely focus on the proxy folder and relink that mov currently there as the original mov file. It seems ultimately what matters is that the braw and proxy file are in the same folder no matter what the folder name is.

Technically both mov files are “proxy” clips made from the braw before they were delivered to me; perhaps with a third party tool. They’re duplicates of each other. Though when I read "Add BRAW Toolbox to Proxy Clips within an event”, I read that to mean, FCP must see that proxy clip in the event as an FCP database designated proxy clip, not a proxy by codec. Therefore I had to have an original clip (the mov file as an original) and I made a duplicate of it in a separate folder so that FCP would designate it as a qualified proxy before I could use this BRAW Toolbox feature. 

Since I can’t import the BRAW Toolbox-generated clip can’t reference a Finder clip I can’t use it as an original clip against a proxy clip (file in the Finder).  I needed to have an original clip and a proxy clip qualified by FCP before I could use this feature. Not sure if this makes sense.


Tangier

**Comment by latenitefilms** [comment]
Basically the Toolbox should probably be renamed to **Add BRAW Toolbox to Video Clips within an Event**.

Yes, the only thing that's really important is that the BRAW file must be in the same path as the MOV file.

**Comment by tangierc** [comment]
Yeah. I don’t know why it doesn’t work for me. I have the files in the right place.

Tangier

**Comment by latenitefilms** [comment]
Can you try on a new library, and basically just follow the exact same steps here and see if it works?

https://github.com/latenitefilms/BRAWToolbox/issues/124#issuecomment-1532247236

**Comment by tangierc** [comment]
This is actually my third attempt even though it’s called test 2. It finally worked. Though like before I couldn’t drag the event which I think led to me sending the XML.

I’ll send the screen recording so you can see my entire process.

Thanks,

Tangier

**Comment by latenitefilms** [comment]
I think MAYBE the issue you're having is that you have a BRAW Toolbox clip already in your event. I THINK it's only expecting to have MOV files in there. Will investigate.

**Comment by latenitefilms** [comment]
I'm going to close this issue in favour of #124.
