### ISSUE TITLE
Clips offline between library launches.

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#108]
Many of my browser and timeline clips will go offline and show the missing effect icon between relaunches of a library. To date, I have never used the effect itself, but only imported using the workflow extension. I will edit normally, close the library and FCP, sleep my computer, come back later to edit and clips that used to be online are now offline. No hard drive or another changes will be made. I'll do a restart of the computer, launch the library and the clips are back again.

Perhaps this an Apple Silicon issue.

M2 Max Macbook Pro / Ventura 13.2.1 / Final Cut Pro 10.6.5

**Comment by latenitefilms** [comment]
And this is with Sandbox Access granted to the drive containing your footage?

**Comment by tangierc** [comment]
I can't verify that. All of the clips have been imported using the extension. Granting sandbox access has done nothing for me. I don't know if I need to reinstall BRTB, but I've done that before and I am nervous that even attempting to do so will break things on this big project. This is why I think the only way I can safely move to the RAID is to make disk images of my current two drives onto the RAID.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as there's already a few issues and discussions going that are all related. I'll try my very best to get to the bottom of the issues you're having.
