### ISSUE TITLE
Show Parameters Won't Work in Inspector

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#109]
The "Show Parameters" feature of my clips in the inspector will not open any parameter window. 

M2 Max Macbook Pro / Ventura 13.2.1 / Final Cut Pro 10.6.5 / BRAW Toolbox 1.06(44)

**Comment by latenitefilms** [comment]
That's very odd. Is the file path in the Inspector valid?

**Comment by latenitefilms** [comment]
Closing in favour of #111.
