### ISSUE TITLE
Feature Request: Make Camera LUT Accessible in Inspector

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#110]
If possible, can the camera LUT pulled from metadata be made available in the setting section of the inspector? If a user doesn't apply the LUT using BRAW Toolbox it would be nice to still have access to the LUT easily on the synced clips like one would with other video files for quick application to one or many clips at a time.

Since I didn't apply it on import, and my Show parameters doesn't work, I have no access to the LUT inside FCP that I can quickly apply to my BRAW Toolbox clips on the timeline. The only option I can see now is to find the LUT from Blackmagic's site (if they make it available), and apply it using a custom LUT Effect. Does this impose more computing resources on the computer than if it were being applied from the settings view and without a custom effect?

**Comment by latenitefilms** [comment]
Unfortunately the **Camera LUT** dropdown in the Final Cut Pro Inspector is only available for video files - not Generators, like BRAW Toolbox is using.

Using a Custom LUT should be fine in this case - it will just be applied after the BRAW decoding in the Final Cut Pro rendering pipeline.

Not being able to press the **Show Parameters** button is definitely a big issue - so I'll try solve this ASAP.
