### ISSUE TITLE
Show perameters not working

### ISSUE THREAD

**Issue by junke104** [latenitefilms/BRAWToolbox#113]
Hi im using a 2019 16" mbp intel

I cant open the parameters in the inspector. getting this error message: 
"
Please select the 'Select BRAW File' button to load a BRAW file before pressing the 'Show Parameters' button, as there's currently no parameters to show.
"

So i select my BRAW file from and then get this error

"
Failed to get IBlackmagicRawJob in populateBRAWParametersWithReset.
"

At this point all of the colours on the image kind of go to a sepia style and I still cant access the parameters.

Very frustrating as have just paid a lot for this app.

**Comment by junke104** [comment]
Also on all clips I've imported via Braw Toolbox none of them have the option to apply stabilisation. How can I get around this? Definitely need access to that feature thanks for your help!

**Comment by latenitefilms** [comment]
Are you importing the BRAW clips via the Workflow Extension?

See: https://brawtoolbox.io/installation/

Regarding stabilisation see: 

https://brawtoolbox.io/stabilisation/

**Comment by latenitefilms** [comment]
Apologies for the delayed reply - I've been on the road.

Are you able to share a screen recording of what's happening?

**Comment by junke104** [comment]
Hi Chris no probs,

Yep sure I uploaded a screen recording for you here: https://we.tl/t-CRtC3yTEmO

Cheers,
Rich

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by latenitefilms** [comment]
You should never have to manually apply the BRAW Toolbox effect.

If you want to modify the RAW parameters you need to double click the Synchronised Clip, click on the Generator on the Primary Storyline and access the BRAW Toolbox effect on that clip.

What you're doing in the screen recording is applying the BRAW Toolbox effect to a clip that already has the BRAW Toolbox clip applied - it's just applied INSIDE the Synchronised Clip.

This is explained in the link I posted above: https://brawtoolbox.io/installation/

Hopefully that solves your issue!
