### ISSUE TITLE
Clips in Timeline went black

### ISSUE THREAD

**Issue by oldsoulsound** [latenitefilms/BRAWToolbox#114]
IF view the actual multi-cam clip it plays fine. When I put it in a project timeline the video goes black.

**Comment by latenitefilms** [comment]
Are you able to share a screenshot? Is it possible you don't have the angle selected?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now as I haven't heard back, but feel free to re-open if you're still having issues.
