### ISSUE TITLE
Green or Blue Frames During Playback

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#12]
Occasionally I will get green or blue frames during playback or scrubbing. Playback performance is choppy as well in FCP, but the same clips perform well in Da Vinci Resolve 18.2 on same computer. Will test on M1 MacBook Pro.

Final Cut Pro 10.6.5
2013 Mac Po 3.5 GHz 6-Core Intel Xeon E5
macOS Monterey version 12.6.2

![Screen Shot 2022-12-30 at 10 12 49 PM](https://user-images.githubusercontent.com/9577806/210140717-7deff43c-5bda-4ab4-a03d-2f5694bfb669.png)

**Comment by latenitefilms** [comment]
That's strange - I haven't seen any green or blue frames on my MacBook Pro (16-inch, 2021, Apple M1 Max, 64 GB RAM).

What GPU(s) do you have in the MacPro?

What resolution is the test BRAW files you're using and from what camera? Can you send me a test clip?

I've made quite a lot of changes in the next beta, so hopefully one of those tweaks fixes that. It should be ready for testing later this week hopefully.

**Comment by tangierc** [comment]
Hi Chris. This footage is not my own so I'd have to get permission to post a clip.

- You're using an M1 so that may be the difference.
- The footage flickers blue and green in FCP when trying to play or scrub, then it will stabilize and try to play, but very choppy. Same braw gets smooth playback in Resolve.
- The GPU is AMD FirePro D500 x 2
- BRAW is 6144x345 @ 23.98 fps

I've been holding out to see what the Mac Pros (Apple Silicon) would be before buying a new desktop this is why I am still on my 2013 Mac Pro and RAID which has been working perfectly to date, and haven't jumped in with the Mac Studio. I have a 2016 MacBook Pro and M1 MacBook Pro, but don't use that as my main editor. Gave the M1 to my son but I can use it to test if need be, although I know you were curious about how this works on Intel Macs.

**Comment by latenitefilms** [comment]
@tangierc - Let me know if you're still seeing issue with Public Beta 2?
