### ISSUE TITLE
Convert BRAW clips to MOV's within an EVENT issue

### ISSUE THREAD

**Issue by leightv** [latenitefilms/BRAWToolbox#123]
Hi,

I've been trying to get the 'Convert BRAW clips to MOV's within an EVENT' to work. I can drag the event into BRAW Toolbox but when I drag the green icon back I get the error:

The dragged XML could not be imported.

The media file cannot be imported. An offline clip was not created because of insufficient data. (format=<empty>:/fcpxml[1]/resources[1]/asset[1])

No such file of directory

Not sure if I'm using this wrong or there's a bug. Can you help?

Leigh

**Comment by latenitefilms** [comment]
Do you have a `.MOV` file in the same folder folder as the `.BRAW` file?
