### ISSUE TITLE
Braw Files won't Import to Final Cut

### ISSUE THREAD

**Issue by bmac773** [latenitefilms/BRAWToolbox#126]
It shows the plus/add when I drag the green box over but it won't import. what am I missing???

**Comment by latenitefilms** [comment]
Are you dragging to the library?

Are you using Final Cut Pro 10.6.5?

We have lots of resources on our website, that should hopefully answer most questions: 

https://brawtoolbox.io

**Comment by bmac773** [comment]
https://user-images.githubusercontent.com/132411721/235809457-88944bef-31e5-443c-bb17-a7f6311c9ffb.mov

This is what happens. could be that im on 10.5.4 smh. I hope thats the issue

**Comment by latenitefilms** [comment]
BRAW Toolbox requires Final Cut Pro 10.6.5 - see:

https://brawtoolbox.io/system-requirements/

The reason it won't drag is because 10.5.4 doesn't support the latest version of FCPXML.
