### ISSUE TITLE
Fatal Error Message when trying to import BRAW files

### ISSUE THREAD

**Issue by nickw34** [latenitefilms/BRAWToolbox#127]
<img width="319" alt="Screenshot 2023-05-07 at 11 07 12 PM" src="https://user-images.githubusercontent.com/132869905/236732472-c9df20d7-354c-49c1-9755-64bb84bbb2b0.png">

I am using a new MacBook Pro 2023 with the M2 Max chip if that helps. It is brand new and I loaded everything up and I can't access my files. On my Mac Studio with a M1 Max chip everything works fine. Not sure what's going on. Any help would be appreciated

**Comment by latenitefilms** [comment]
Have you installed everything?

See: https://brawtoolbox.io/installation/

**Comment by latenitefilms** [comment]
I'm going to assume that running the main BRAW Toolbox application fixed the issue, but feel free to re-open this issue if you're still having problems!
