### ISSUE TITLE
Relink BRAW Clips Without Creating New Events

### ISSUE THREAD

**Issue by tangierc** [latenitefilms/BRAWToolbox#131]
If this is possible, it would be helpful to be able to relink braw clips in events without having to generate new events; particularly when a library has a lot of events. This was would also be useful when moving projects to a new folder, drive, or computer.

**Comment by latenitefilms** [comment]
Agreed - I'll have a proper look into this this coming week. Stay tuned.

**Comment by latenitefilms** [comment]
This will be fixed in v1.1.3.
