### ISSUE TITLE
Visual Dropouts Fixed With Opacity

### ISSUE THREAD

**Issue by airwindows** [latenitefilms/BRAWToolbox#132]
I'm not sure what's going on, but I've had one dropout where a clip showed three frames of an upside-down BRAW Toolbox poster image, and another clip showed one frame of black. I could isolate these by trimming around them with the blade tool.

In both cases, when I went to drop the opacity and fall through to a lower clip, the image came right back once it was off 100% opacity, so I'm using that as a workaround. Instead of a flash of random frame or black, it's a flash of the underlying clip peeking through very faintly.

I'm not unhappy with BRAW Toolbox, just thinking this is very weird and calling your attention to it :)

**Comment by latenitefilms** [comment]
That's strange. Are you using Multicam Clips or Synchronised Clips?

Any chance you could share a screen recording of this?

**Comment by airwindows** [comment]
No. I had work and couldn't resume until the following week. I got a one-frame black visual drop-out and set about recording the screen in 'IShowU Instant', then edited all layers with cmd-shift B for blade all, expecting to fade the black frame a tiny amount and make it pop into existence again. Instead, it just came back without being isolated or faded.

Then I checked the screen capture and it had only recorded a black screen area with mouse pointer overlaid. I'm sorry.

I'll follow up more if I'm able to do it again. This is on a fresh project with two layers of braw and a layer of laptop screen capture (works on that) playing at all times. For what it's worth, I am not seeing this happen when there's only one layer of braw, or seeing any evidence it's happening on the underlying layer. Seems like just the top layer and it seems like I'm able to find workarounds. Haven't found a workaround for not being able to screen capture: this machine has given me trouble with that before, which is why I record the laptop.

**Comment by airwindows** [comment]
Found an even better workaround. Instead of changing opacity, any change in blend mode seems to bring the frame back. And if I use 'premultiplied mix' it appears to be the same as 'normal' so I can do an artifactless workaround. I'm sorry I can't give you more but I'm glad I'm able to wrestle it back into shape.

I don't know what kind of clip I'm using, I'm using v1.1.2(49) and not altering any settings other than the BRAW settings I need. I forgot 'use video black level' and successfully went back and adjusted both long clips by clicking until I got through to the black screen and the BRAW settings for the actual clip, so in practical terms this is working. I just don't know why it loses frames, or whether it has to do with the blend mode/opacity with two BRAW videos on top of each other, only that I'm able to get the video back by altering those details, and it'll return to the black frame if I set it back to 100% and 'normal'.

**Comment by latenitefilms** [comment]
Are your BRAW clips Multicam Clips or Synchronised Clips in the timeline/browser?

Are you able to share a screenshot (just a still) of your timeline?

It sounds like it might be a Final Cut Pro bug rather than anything specifically wrong with BRAW Toolbox.

In theory, at least, if a BRAW clip plays back fine and correctly in the Browser, it should work correctly in the timeline, and if it doesn't, it's most likely something going wrong deep within Final Cut Pro.

BRAW Toolbox is doing something somewhat unconventional (i.e. a Generator with an Effect within a Sync Clip within a Multicam Clip) - so it's entirely possible that we're hitting edge cases in Final Cut Pro that the developers never thought of or considered.

If screen recording isn't working, can you just record the screen with your phone instead? You can also just try using QuickTime Player to record the screen instead?

I'll try and reproduce on my end, but if the BRAW clip is playing fine in the Browser, I'm not sure there's much we can do.

You can try Compound Clipping things to see if that makes any difference?

**Comment by airwindows** [comment]
I don't know how to tell whether they're Multicam Clips or Synchronized Clips in the timeline. I can give you whatever screenshots you like, though I'm not seeing the 'upside down BRAW graphic' this time, only black frames.

If it is a Final Cut bug having to do with the luma key (has to be that) interfering with BRAW Toolbox, I'm happy to use workarounds to the bug. I don't know how to Compound Clip things :)

**Comment by latenitefilms** [comment]
This is a Multicam Clip:

<img width="261" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/1b41f00e-a985-4569-94b2-c826bcc192c7">

This is a Synchronised Clip:

<img width="373" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/5bdb0103-213c-46fe-9972-aeac0fabe71a">

You can press **OPTION+G** or right-click on a Clip to "move it" into a Compound Clip:

<img width="324" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/f1503e52-b4f2-4348-b896-01df97b936d3">

I just tried putting a Luma Key on a BRAW clip onto of another BRAW clip and it all worked fine here:

<img width="2168" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/1ed76bb2-281a-4567-a092-6f7c8dba263b">

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but yell out if you have any further questions!
