### ISSUE TITLE
All BRAW Files are Missing when switching between computers

### ISSUE THREAD

**Issue by spencedeezy** [latenitefilms/BRAWToolbox#136]
Whenever I switch between my laptop and desktop i have to manually re-link every BRAW file. Is there a way around this? Or a faster way than going one by one?

**Comment by latenitefilms** [comment]
Yes, if the file path is the same between machines, if you manually Grant Sandbox Access you can move between machines.

See: https://brawtoolbox.io/collaboration/

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but yell out if you run into any issues!
