### ISSUE TITLE
Plug-in is not responding

### ISSUE THREAD

**Issue by egayton55** [latenitefilms/BRAWToolbox#139]
When Dragging my BRAWFiles into my Final Cut Pro library it comes up with "A plug is-In is not responding" paid £79.99 for this to not work, honestly really mad

**Comment by latenitefilms** [comment]
There are now thousands of users using BRAW Toolbox everyday, including on feature films and television series, so this is definitely not usual behaviour.

Do you need all the system requirements? 

See: https://brawtoolbox.io/system-requirements/

Are you able to send us your Log Files & Crash Logs? 

See: https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

It seems that @spencedeezy is also running into a similar issue in #137, however in their case it seems to be related to some specific BRAW files, which might mean it's a bug in the Blackmagic RAW SDK itself.

Do you have the same issue if you use some sample clips from the Blackmagic website?

See: https://brawtoolbox.io/faq/#where-can-i-find-some-sample-braw-clips

**Comment by latenitefilms** [comment]
I haven't heard back, so I'm going to close this issue for now, but yell out if you're still having problems.
