### ISSUE TITLE
Having issues importing Braw to my library "drag and drop " .... when I drag my converted Braw footage , all the footage comes up red with only audio. Can you help with this please

### ISSUE THREAD

**Issue by Sallen307** [latenitefilms/BRAWToolbox#144]

**Comment by latenitefilms** [comment]
It sounds like the plugin is not loaded properly. Make sure you've followed all the installation instructions here:

https://brawtoolbox.io/installation/

...then try restarting your computer to give Final Cut Pro a clean slate.

**Comment by Sallen307** [comment]
Uninstalling and reinstalling solved the issue... thanks

**Comment by latenitefilms** [comment]
Great news! Happy cutting!
