### ISSUE TITLE
Red line on timeline after Braw footage has been imported to time line

### ISSUE THREAD

**Issue by Sallen307** [latenitefilms/BRAWToolbox#147]
After converting Braw footage and drag and dropped to time line I get choppy play back and a red line above my timeline. What can this be?![image](https://github.com/latenitefilms/BRAWToolbox/assets/139857037/50fd997b-fe46-4f26-96df-c8271e2bbecf)

**Comment by latenitefilms** [comment]
The red line is some internal Final Cut Pro developer tool - generally meaning there's some kind of frame-rate mismatch internally within Final Cut Pro.

Are your clips the same frame rate as your timeline?

As for choppy playback, what Decode Quality are you using?

**Decode Quality** allows you to select the decode quality of the BRAW files. There are two "special" options that you won't find in DaVinci Resolve, **Automatic (HD)** and **Automatic (UltraHD)**. These options will automagically pick the best decode quality based on the HD or UltraHD delivery.

If you're working in a HD timeline, we recommend just using the Automatic (HD) option, then using the **Force Full Quality** option in the Final Cut Pro Inspector when you're ready to export or render at full quality.

However, if you're working with 8K or 12K BRAW, you might need a much lower decode quality for editing.

It's worth doing these speed tests to see if your system can actually handle BRAW:

https://brawtoolbox.io/troubleshooting/#is-my-mac-fast-enough-to-play-braw-files

Hope this helps!

**Comment by Sallen307** [comment]
Thank you … I’ll try all

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but feel free to re-open if you're still having issues.
