### ISSUE TITLE
Show Parameters Not Working

### ISSUE THREAD

**Issue by bencwilson** [latenitefilms/BRAWToolbox#149]
I just purchased the BRAW Toolbox plugin and have installed it successfully, but every time I click on a .braw video file that I've imported into FCPX (v 10.6.8) and click on the Video Inspector, it does not show me any of the parameters to control metadata values like ISO, exposure, etc.  When I click the "Show Paramaters" button it just pops up an error message that says "An Error Has Occurred.  Failed to get IBlackmagicRawJob in populateBRAWParametersWithReset."

Please let me know what I can do to get this plugin working properly as it's critical to our workflow with the new Ursa 12K camera we've just purchased.  I have already tried restarting FCPX, deleting FCPX preferences and relaunching, and tried restarting my iMac.

**Comment by latenitefilms** [comment]
I've responded to Ben's email directly.

**Comment by bencwilson** [comment]
Thanks so much, Chris!
