### ISSUE TITLE
Final Cut Pro X 10.6.10 Relink BRAW Clips within an LIBRARY / EVENT / PROJECT not working right

### ISSUE THREAD

**Issue by thewayzof151** [latenitefilms/BRAWToolbox#156]
when I use the tool to relink the files, instead of giving the option to replace, it just creates a completely separate event and doesn't relink the files in the timeline because of it. Now I have a broken copy and a working copy but timeline is still on the broken copy. Please assist

**Comment by latenitefilms** [comment]
Apologies for the delayed reply!

I assume you're running the latest version of BRAW Toolbox?

After relinking you should get a dialog from Final Cut Pro like this:

<img width="260" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/ea81ef18-8c74-436f-bc2a-1e95784aa9d4">

...where you can "replace" the original clips.

If you don't see this popup, it's possible you have clicked "Do not ask again" previously?

You should be able to reset the "Do not ask again" warning, but clicking "Reset All" in Final Cut Pro's General Preferences/Settings:

<img width="409" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/7a14c1a1-79a1-4707-b0a7-b8ebc715ffa6">

If pressing "Reset All" doesn't work, you can try [trashing your Final Cut Pro Preferences](https://support.apple.com/en-au/HT203477#:~:text=Reset%20Final%20Cut%20Pro%20preferences,-Resetting%20preferences%20doesn&text=Choose%20Final%20Cut%20Pro%20%3E%20Settings,Click%20Delete%20Preferences.) by holding down OPTION+COMMAND whilst starting Final Cut Pro from the dock.

Another thing you can try is dragging your library into the BRAW Toolbox, as opposed to an event. I'd suggest making a backup of your library before doing this for safety.

I just did a test moving a BRAW file from "FOLDER 1" to "FOLDER 2", and it works correctly here:

<img width="870" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/762183b3-9558-4960-82d9-a8090cf719ef">

Generally speaking, I try and avoid having to manually relink things working with BRAW Toolbox. If we're doing Collaboration, we generally recommend everyone just having the same drive path - as it's just heaps easier.

Hope this helps!

I'm going to close this issue for now, but feel free to re-open or yell out if you need any further assistance or if anything is unclear!
