### ISSUE TITLE
BRAW shots suddenly just colored solids

### ISSUE THREAD

**Issue by t3dc** [latenitefilms/BRAWToolbox#157]
Hi there,

Love the plugin so far, but having another issue. I'm hoping there's an easy fix. 

Quite suddenly, all of the braw files no longer display video. Instead I get a solid color which varies in brightness as I scrub through the footage (see screenshot). No updates or changes to the system were made -- though I've since updated and reinstalled everything. No change. I also tried transcoding to mov. Mov files import fine, but the "Convert BRAW clips to MOV's within an event" tool processes my footage, but won't add it back to my library. I don't get an error, it just does nothing as I would expect if I were dragging to an event.

If I create a brand new library and import a braw clip using braw toolbox, it comes in as colored solids.

Ventura 13.6
FCPX 10.6.10
BrawToolBox 1.3.2 (57)

Please help! Project is stalled and missing deadlines.

![Screenshot 2023-10-17 at 11 16 35](https://github.com/latenitefilms/BRAWToolbox/assets/52919338/256db9bc-05ba-4478-b9f9-d3cee37a0051)

**Comment by t3dc** [comment]
> Just to confirm, if you try and import a BRAW clip in a completely new Library via the Workflow Extension, it just comes across as a solid colour? What happens when you step inside the Multicam clip, then step inside the Synchronised clip and modify the BRAW Toolbox effects attributes like Exposure?

1.3.2 (57) - re-ran the import test, same result. Adjustments to effects attributes work as you would expect. I.E. if you increase exposure, the solid color gets brighter/moves toward white.

Upgrading to 1.3.3 (59) we're now getting the "this plugin is not responding" error. If we can get past that, I'll let you know.

Unfortunately, we don't have a backup of 1.3.0. Is that something we can download from github somehow?

**Comment by t3dc** [comment]
> If it doesn't, I've been trying to help another user that's having some weird problems on an older Intel Mac, so if you send me your email address, I can try ad you to that TestFlight build.

Happy enough to send along my email, but would prefer not to post it to github. What's the best method of getting it to you?

**Comment by latenitefilms** [comment]
When you open the main BRAW Toolbox application - are all the latest Motion Templates installed?

See: https://brawtoolbox.io/installation/

> 1.3.2 (57) - re-ran the import test, same result. Adjustments to effects attributes work as you would expect. I.E. if you increase exposure, the solid color gets brighter/moves toward white.

That's super, super weird. I've never seen anything like that before and not even sure how it's even possible.

> Upgrading to 1.3.3 (59) we're now getting the "this plugin is not responding" error. If we can get past that, I'll let you know.

It would be great if you could send me any crash logs, along with new copies of the log files you've already posted above.

See: https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

> Happy enough to send along my email, but would prefer not to post it to github. What's the best method of getting it to you?

You can contact me via: https://brawtoolbox.io/support/

**Comment by t3dc** [comment]
> That's super, super weird. I've never seen anything like that before and not even sure how it's even possible.

Not sure if it helps, but the color appears to come from the video. Almost like it's just grabbing one pixel and making it full screen.

**Comment by latenitefilms** [comment]
Super strange! So it was working fine, then one day it just started doing this?

Have you tried trashing FCPX's Preferences?

**Comment by t3dc** [comment]
> Have you tried trashing FCPX's Preferences?

Oh yes. Repeatedly. :( I'm out of the office today, but will try to get you additional logs and such first thing tomorrow.

**Comment by t3dc** [comment]
> Super strange! So it was working fine, then one day it just started doing this?

Yeah. I was tweaking the edit on a scene and decided to change out one take for another. All of them were in the bin already and had been for weeks at this point. I selected my in and out, drug it to the timeline and it was just green. No video. I started troubleshooting and finally, deleted all the existing render files. At that point EVERY clip was just a solid color. So, I don't know when it broke. Apparently, I'd been floating along on the render cache for some period of time.

**Comment by t3dc** [comment]
Actually, I bet that's the answer. I bet it was working on 1.3.0 and we didn't spot that it had broken with the update, because the render cache kept showing us working footage.

**Comment by latenitefilms** [comment]
Given this issue is now a month old, I'm going to close this for now, but feel free to re-open if you're still having issues or if you have any questions.

If you're still having issues with **BRAW Toolbox v1.3.4 (62)** please let me know.

**Comment by t3dc** [comment]
Thanks, Chris. I saw the new beta was out and haven’t had a chance to try it yet. But based on release noted it does sound like it will get me sorted. Thanks so much for all your help!Sent from my iPhoneOn 16 Nov 2023, at 22:55, Chris Hocking ***@***.***> wrote:﻿
Given this issue is now a month old, I'm going to close this for now, but feel free to re-open if you're still having issues or if you have any questions.
If you're still having issues with BRAW Toolbox v1.3.4 (62) please let me know.
