### ISSUE TITLE
Tool box glitches or frame rate issue 

### ISSUE THREAD

**Issue by Gilly1222** [latenitefilms/BRAWToolbox#161]
Hi 
I normally film in pro res / mov files and use final cut. 
but mistake I film a shoot in Braw files. 

So Brough the plug Braw Tool box and added to final cut. 

The files play /normally in BlackMagic Raw... but when playing on tool box in final cut. 
It looks like the frame rate off.. of glitches... not playing smoothly. 

I did film some in real speed of 25 frames and also in slow-motion but but have same result. 

paid $80 for the plug in... so gutted its not working for me. 

Thanks 
Adam

**Comment by latenitefilms** [comment]
Is it just not playing back in realtime, or is it not working even if you go frame-by-frame or render? When you say "glitches", can you share a screenshot of what you're seeing?

If it's just playback performance can you just edit in a lower decode quality and then force to full for exports/render?

What are your Mac specs? What version of macOS and FCPX?

**Comment by latenitefilms** [comment]
I haven't heard back from you Adam, so I'm going to close this issue for now - but please feel free to re-open it if you're still having issues or have any questions.
