### ISSUE TITLE
Sony SLOG3 RAW/EI Control

### ISSUE THREAD

**Issue by MysticX144** [latenitefilms/BRAWToolbox#164]
I would like to have access to the same controls as Sony Catalyst Browse/Prepare in Final Cut Pro. Having the ability to adjust the native SLOG3, EI settings, Exposure, Temp, Tint, etc. I hope this request makes sense.  should be similar to how RED raw and Apple Pro Res Raw adjustments can be made

**Comment by latenitefilms** [comment]
@MysticX144 - Are you able to share some test clips?

**Comment by MysticX144** [comment]
I tried it said the file type wasn't supported, should I zip it and upload ?

**Comment by latenitefilms** [comment]
You can upload here: https://latenitefilms.digitalpigeon.com

**Comment by MysticX144** [comment]
Just uploaded a fileSent from my iPhoneOn Dec 13, 2023, at 5:02 PM, Chris Hocking ***@***.***> wrote:﻿
You can upload here: https://latenitefilms.digitalpigeon.com

**Comment by latenitefilms** [comment]
Got it, thank you!

**Comment by latenitefilms** [comment]
Unfortunately, I think this is outside the scope of BRAW Toolbox for now, so closing this issue. Will definitely keep this in mind for future products though!

**Comment by MysticX144** [comment]
I appreciate the consideration Sent from my iPhoneOn Sep 8, 2024, at 8:56 PM, Chris Hocking ***@***.***> wrote:﻿
Unfortunately, I think this is outside the scope of BRAW Toolbox for now, so closing this issue. Will definitely keep this in mind for future products though!
