### ISSUE TITLE
Clips Unlinked, 

### ISSUE THREAD

**Issue by tommyanderson66** [latenitefilms/BRAWToolbox#165]
So I have the Toolbox currently installed. I edited a full project a few weeks ago, and now when I went to reopen the file, all of the BRAW clips are not working, and I get the error in the first screenshot. I am attempting to allow the sandbox access, but when I drop the toolbox on a random clip, it doesn't show in the inspector panel. 

I went through the troubleshooting of uninstalling then reinstalling the Toolbox.

When I reinstalled, I did not get prompted to give permission to the metadata (which I believe may be the error?) But the thumbnails aren't updating.

Any advice?

<img width="485" alt="Screenshot 2023-12-22 at 12 46 24 PM" src="https://github.com/latenitefilms/BRAWToolbox/assets/154634940/5450d9a1-0ce1-49e4-acf5-9ab72e93c60f">

<img width="692" alt="Screenshot 2023-12-22 at 12 45 37 PM" src="https://github.com/latenitefilms/BRAWToolbox/assets/154634940/327bc733-c198-4c38-b8f3-5b6bc1f90576">
<img width="477" alt="Screenshot 2023-12-22 at 12 45 42 PM" src="https://github.com/latenitefilms/BRAWToolbox/assets/154634940/5c6dcf74-732a-448f-a92a-8ba83a58cf0b">
<img width="693" alt="Screenshot 2023-12-22 at 12 46 21 PM" src="https://github.com/latenitefilms/BRAWToolbox/assets/154634940/4568eca7-4efc-40bc-b479-32c89a64ac0d">

**Comment by latenitefilms** [comment]
Have you read this page?

https://brawtoolbox.io/relinking/

**Comment by latenitefilms** [comment]
Also, in this screenshot:

![image](https://github.com/latenitefilms/BRAWToolbox/assets/22286696/21f8327d-7e1d-4ac8-b301-7ea6f5c7a779)

You're hiding all the effects, so just press the "show" button to show them.

**Comment by tommyanderson66** [comment]
Sweet, thanks for the help!

So now that I'm starting to connect them manually with the "Select BRAW
File" option, the videos are starting to show up in the timeline. However,
the clips are not keeping the same selected edited time that they were
before. Does that make sense? Let me know if there's a way to get those
effects/timeline back in there.

Best,

**Comment by latenitefilms** [comment]
I believe this issue was solved via email, so closing for now.
