### ISSUE TITLE
Final Cut Pro crashes when importing BRAW Toolbox FCPXML on macOS Sonoma 14.3

### ISSUE THREAD

**Issue by Sallen307** [latenitefilms/BRAWToolbox#167]
Final Cut Pro crashes when I drag be raw clips from BRAW Toolbox to Final Cut Pro library . I've been using BRAW Toolbox for almost a year now, and never had this issue. I have also Install and reinstalled Final Cut Pro and BRAW Toolbox plug-in. I've also tried using Bro clips from previous projects and still have the same issue with Final Cut Pro crashing when transferring to library. Any help with this issue?

**Comment by latenitefilms** [comment]
That's strange. When you drag the icon from BRAW Toolbox's Workflow Extension to Final Cut Pro, all you're doing is dragging a FCPXML - so if Final Cut Pro is crashing, then it must be some kind of bug in Final Cut Pro.

Can you please share the crash log?

Did it only start happening after updating to Final Cut Pro 10.7.1?

What happens if you try and drag `~/Library/Group Containers/A5HDJTY9X5.com.latenitefilms.BRAWToolbox/Library/Application Support/Last Export.fcpxml` into Final Cut Pro?

Note that this is your user library - you can find out how to access it here:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

The above article also explains how to get BRAW Toolbox crash logs and log files.

**Comment by Sallen307** [comment]
I don't believe this has started with the 10.7.1 update. I did recently update my Mac iOS to Sonoma 14.3 but I don't know if that should be the cause. When importing  Last Export.FCPXML it also crashes . if I click on  Export.FCPXML with Final Cut Pro closed it will open Final Cut and then it will be there.

[Final Cut Pro-2024-01-27-170951.ips.zip](https://github.com/latenitefilms/BRAWToolbox/files/14073991/Final.Cut.Pro-2024-01-27-170951.ips.zip)

here's the crash log.

**Comment by latenitefilms** [comment]
Note to self - here's the important parts of the above crash log:

```lua
Process:               Final Cut Pro [2292]
Path:                  /Applications/Final Cut Pro.app/Contents/MacOS/Final Cut Pro
Identifier:            com.apple.FinalCut
Version:               10.7.1 (410082)
Build Info:            ProEditor-41000082016000000~12 (1D1004)
App Item ID:           424389933
App External ID:       861999800
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-27 17:09:51.4268 -0500
OS Version:            macOS 14.3 (23D56)
Report Version:        12
Anonymous UUID:        5408C6B5-9B1A-2820-1DA2-4DAED9C312A4

Sleep/Wake UUID:       9A292848-1A4E-43FF-BD93-4E5870BAC4BD

Time Awake Since Boot: 2900 seconds
Time Since Wake:       2384 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Final Cut Pro [2292]

Application Specific Information:
abort() called


Application Specific Backtrace 0:
0   CoreFoundation                      0x000000018d79c540 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x000000018d28deb4 objc_exception_throw + 60
2   CoreFoundation                      0x000000018d7c188c _CFBundleGetValueForInfoKey + 0
3   Flexo                               0x000000010bec5808 -[FFAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 720
4   Flexo                               0x000000010c0f933c -[FFAnchoredObject setClippedRange:] + 1028
5   Flexo                               0x000000010c2c30f0 -[FFAnchoredCollection setClippedRange:] + 104
6   Flexo                               0x000000010c3f43f8 -[FFXMLImporter(AssetClipImport) addAssetClip:toObject:parentFormatID:] + 452
7   Flexo                               0x000000010c55bc2c -[FFXMLImporter(StoryImport) addEdits:toObject:xmlParent:parentFormatID:] + 536
8   Flexo                               0x000000010c55c8c8 -[FFXMLImporter(StoryImport) addEditContainer:toObject:parent:parentFormatID:xmlSource:xmlParent:] + 2228
9   Flexo                               0x000000010c67ffa0 -[FFXMLImporter(MediaComponentImport) addEffectComponent:toObject:parentFormatID:] + 240
10  Flexo                               0x000000010c8fd014 -[FFXMLImporter(VideoImport) addVideo:toObject:parentFormatID:] + 44
11  Flexo                               0x000000010c55bbc4 -[FFXMLImporter(StoryImport) addEdits:toObject:xmlParent:parentFormatID:] + 432
12  Flexo                               0x000000010c55c360 -[FFXMLImporter(StoryImport) addEditContainer:toObject:parent:parentFormatID:xmlSource:xmlParent:] + 844
13  Flexo                               0x000000010bf540d0 -[FFXMLImporter(SyncClipImport) addSyncClip:toObject:parentFormatID:] + 280
14  Flexo                               0x000000010c55bc94 -[FFXMLImporter(StoryImport) addEdits:toObject:xmlParent:parentFormatID:] + 640
15  Flexo                               0x000000010c55bfac -[FFXMLImporter(StoryImport) performAudioPreflightCheckForObject:nodeKey:xmlParent:parentFormatID:storyItems:isAudioOnlyCollection:shouldWrapAudioMediaComponents:] + 332
16  Flexo                               0x000000010c55c29c -[FFXMLImporter(StoryImport) addEditContainer:toObject:parent:parentFormatID:xmlSource:xmlParent:] + 648
17  Flexo                               0x000000010c559400 -[FFXMLImporter(MulticamImport) newMulticamAngle:parentFormatID:] + 216
18  Flexo                               0x000000010c559210 -[FFXMLImporter(MulticamImport) addMulticamAngle:toObject:parentFormatID:] + 100
19  Flexo                               0x000000010c559110 -[FFXMLImporter(MulticamImport) addMulticam:toObject:] + 208
20  Flexo                               0x000000010c559004 -[FFXMLImporter(MulticamImport) newMulticamMedia:name:identifier:eventProject:error:] + 204
21  Flexo                               0x000000010ca69e2c -[FFXMLImporter(MediaImport) copyClipRef:type:xmlSource:error:] + 672
22  Flexo                               0x000000010c559830 -[FFXMLImporter(MulticamImport) newMulticamClip:inParent:parentFormatID:error:] + 148
23  Flexo                               0x000000010c559728 -[FFXMLImporter(MulticamImport) newMulticamOwnedClipsItem:] + 36
24  Flexo                               0x000000010c5a7600 -[FFXMLImporter(EventImport) copyEventClipsByImportingEvent:intoEventProject:error:] + 884
25  Flexo                               0x000000010c5a7064 -[FFXMLImporter(EventImport) processEventProjectContentsInto:error:] + 584
26  Flexo                               0x000000010c097e4c -[FFXMLImporter importProjectsFromFCPXMLDocument:event:error:] + 496
27  Flexo                               0x000000010c09848c -[FFXMLImporter import:] + 716
28  Flexo                               0x000000010c5e9a48 +[FFXML importFromXMLData:options:taskDelegate:warnings:error:] + 164
29  Flexo                               0x000000010c949398 -[FFXMLTranslationTask importClipsWithOptions:taskDelegate:] + 140
30  Flexo                               0x000000010c9492ec -[FFXMLTranslationTask importClipsWithOptions:] + 64
31  Flexo                               0x000000010c949288 -[FFXMLTranslationTask importWithOptions:] + 20
32  Final Cut Pro                       0x0000000104890b0c -[PEAppController openXMLDocumentWithURL:bundleURL:display:sender:] + 120
33  Final Cut Pro                       0x0000000104890a1c -[PEAppController application:openFile:] + 564
34  AppKit                              0x000000019133ebe0 -[NSApplication _doOpenFile:ok:tryTemp:] + 324
35  AppKit                              0x0000000191350840 __88-[NSApplication(NSAppleEventHandling) _openURLs:requestedBySourceApp:completionHandler:]_block_invoke.41 + 292
36  AppKit                              0x00000001913505e0 withWindowOrderingObserverHeuristic + 544
37  AppKit                              0x0000000191350124 -[NSApplication(NSAppleEventHandling) _openURLs:requestedBySourceApp:completionHandler:] + 1108
38  AppKit                              0x0000000191164a2c __69-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]_block_invoke + 564
39  AppKit                              0x0000000191164774 -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] + 244
40  AppKit                              0x0000000190f0a750 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 412
41  Foundation                          0x000000018e808374 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 316
42  Foundation                          0x000000018e808168 _NSAppleEventManagerGenericHandler + 80
43  AE                                  0x0000000194692dc0 _AppleEventsCheckInAppWithBlock + 13808
44  AE                                  0x00000001946926e8 _AppleEventsCheckInAppWithBlock + 12056
45  AE                                  0x000000019468bcf8 aeProcessAppleEvent + 488
46  HIToolbox                           0x0000000197cfe2d4 AEProcessAppleEvent + 68
47  AppKit                              0x0000000190f051dc _DPSNextEvent + 1440
48  AppKit                              0x00000001916efeec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
49  AppKit                              0x0000000190ef837c -[NSApplication run] + 476
50  LunaKit                             0x0000000104f87cb0 LKApplicationMain + 204
51  dyld                                0x000000018d2c90e0 start + 2360


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18d6120dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18d649cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x18d555a40 abort + 180
3   Flexo                         	       0x10cac0ca4 FFApplicationHandleExceptionThatShouldNotBeIgnored.cold.1 + 156
4   Flexo                         	       0x10c682790 FFApplicationHandleExceptionThatShouldNotBeIgnored + 196
5   Foundation                    	       0x18e808218 _NSAppleEventManagerGenericHandler + 256
6   AE                            	       0x194692dc0 0x194687000 + 48576
7   AE                            	       0x1946926e8 0x194687000 + 46824
8   AE                            	       0x19468bcf8 aeProcessAppleEvent + 488
9   HIToolbox                     	       0x197cfe2d4 AEProcessAppleEvent + 68
10  AppKit                        	       0x190f051dc _DPSNextEvent + 1440
11  AppKit                        	       0x1916efeec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  AppKit                        	       0x190ef837c -[NSApplication run] + 476
13  LunaKit                       	       0x104f87cb0 LKApplicationMain + 204
14  dyld                          	       0x18d2c90e0 start + 2360
```

It's crashing somewhere in the FCPXML importer, but I have no idea why, or what is causing it, especially if BRAW Toolbox was working fine prior to updating macOS.

I'll try updating to macOS Sonoma 14.3 and see if that has any impact on my machine.

Can you share the `Last Export.fcpxml` as well?

**Comment by latenitefilms** [comment]
It shouldn't make any difference, but the only thing I can think of... You could try turning off (or on) **Create Multicam Clips** in the BRAW Toolbox Workflow Extension settings?

<img width="381" alt="image" src="https://github.com/latenitefilms/BRAWToolbox/assets/22286696/7ea9b879-e2be-410e-b2ae-75e3518a51db">

**Comment by Sallen307** [comment]
[Last Export.fcpxml.zip](https://github.com/latenitefilms/BRAWToolbox/files/14074179/Last.Export.fcpxml.zip)

Thanks for looking in to this. it's totally weird no issues before this update I believe.

**Comment by Sallen307** [comment]
No difference when turning off, create multicam clips

**Comment by latenitefilms** [comment]
That FCPXML imports fine on my machine (16-inch 2021 MacBook Pro, M1 Max, 64GB RAM, 8TB SSD) running Final Cut Pro 10.7.1 and macOS Sonoma 14.1.2, so it's definitely not a BRAW Toolbox bug - it's something breaking Final Cut Pro's FCPXML import.

Have you tried trashing your Final Cut Pro preferences?

**Comment by latenitefilms** [comment]
I'm downloading macOS Sonoma 14.3 now, so we'll see what that brings.

**Comment by Sallen307** [comment]
Yes, I deleted final cut preferences. Still crashes.

**Comment by latenitefilms** [comment]
I just updated to macOS Sonoma 14.3 and importing your FCPXML works fine here, so it's not something specific to macOS Sonoma 14.3.

I'll reach out to the Final Cut Pro Team and see if they have any ideas.

Could any regional settings have changed recently? Have you changed from using a "." to a "," (or similar) for decimal separators, etc?

**Comment by Sallen307** [comment]
No regional settings have been changed. This is all of a sudden.

**Comment by latenitefilms** [comment]
All I can really suggest is to contact Apple Support - as it's definitely a Final Cut Pro bug, as it's crashing even when you just try and import a FCPXML.

I'll chase Apple myself too.

You could also try create a new macOS User and see if the problem happens in a new user account?

**Comment by Sallen307** [comment]
There's no issue with importing  FCPXML files. I just imported a couple XML projects as test. Those seem to come in fine. 

I'll try new User and let you know that works. 

Thanks!

**Comment by latenitefilms** [comment]
Any chance you could export App Diagnostics from Final Cut Pro so that I can share them with the Final Cut Pro team?

See: https://fcp.cafe/bugtracker/#final-cut-pro-diagnostics-bundle

I'll create a new issue over at FCP Cafe.

**Comment by latenitefilms** [comment]
Reported on FCP Cafe (and Apple's Feedback Assistant) here: https://github.com/CommandPost/FCPCafe/issues/333

**Comment by Sallen307** [comment]
Sure thing I'll run the diagnostics now and thank you

**Comment by Sallen307** [comment]
[VideoAppDiagnostics-FinalCut-2024-01-27-195121.tar.gz](https://github.com/latenitefilms/BRAWToolbox/files/14074442/VideoAppDiagnostics-FinalCut-2024-01-27-195121.tar.gz)

**Comment by Sallen307** [comment]
is there anything you recommend that I do to or speak with that can help solve my issue.

**Comment by latenitefilms** [comment]
The only thing I can suggest is try another user account or contact Apple Support:

https://support.apple.com/en-au/final-cut-pro

**Comment by Sallen307** [comment]
ok thanks. I just downloaded a trail version Color Finale Transcoder and it worked with ease. I'll try all your suggestions! thanks for the help and ill keep you updated.

**Comment by Sallen307** [comment]
Also crashed on different User Account. Reaching out to apple support next.

**Comment by latenitefilms** [comment]
If you just want to convert BRAW to ProRes, then DaVinci Resolve is the best free option. You can also look at Hedge's EditReady.

Have you tried moving a single BRAW file to your desktop? Does that work with BRAW Toolbox?

**Comment by Sallen307** [comment]
Yes. I did end up using Da Vinci to convert to Pro Res, but I really
appreciate the Braw tool box work flow.

I have a quite a few Braw files on my desktop. Not sure what you mean by
“Moving a single Braw clip to desktop means”.

**Comment by Sallen307** [comment]
<img width="938" alt="Screenshot 2024-01-28 at 7 26 49 PM" src="https://github.com/latenitefilms/BRAWToolbox/assets/139857037/7d43945c-afc0-4668-a504-eb2ffe2eb530">

Just Spoke with Apple support. They believe the problem lies somewhere between the latest Software updates that taken place in the past few days. , right now Final Cut Pro, BRAW Toolbox, and Sonoma 14.3. were the last to be updated. No solution yet. They're going to get back to me  after they evaluate looking FCPX crash report. Thanks for your help and awareness.

**Comment by latenitefilms** [comment]
I'll let you know if I hear anything from the Final Cut Pro team.

**Comment by Sallen307** [comment]
thanks

**Comment by Sallen307** [comment]
BRAW Toolbox started working again, miraculously. Thanks for always being responsive and aware thanks
