### ISSUE TITLE
Drag and Drop to Add Files to List

### ISSUE THREAD

**Issue by TheDaveChap** [latenitefilms/BRAWToolbox#17]
It's clear there's a button to "Import BRAW Files", but wonder if it's possible to add drag-drop functionality to this list, so users can drag a selection of BRAW files from the Finder here without hopping into a Finder browser window. I find myself dragging/dropping and realizing I need to hop through that button/finder workflow. Muscle memory and all.

**Comment by latenitefilms** [comment]
Yes, agreed - I definitely intend to add this. It's just slightly more tricky with sandboxing, but will try and solve in next public beta.

**Comment by latenitefilms** [comment]
This will be included in the next beta.
