### ISSUE TITLE
Plug-in Not Responding

### ISSUE THREAD

**Issue by PixelVideo** [latenitefilms/BRAWToolbox#174]
I just installed BRAW Toolbox and after importing the BRAW clips into FCP I get the error " The Plug-in BRAWPlugin is not responding.  This plug-in will be disabled"

I do have sound, just no video.

I restarted the Mac and deleted FCP prefs

I tried to uninstall the app using your uninstaller but it failed.  Here are some screen shots

![Screenshot 2024-05-16 at 10 30 56 AM](https://github.com/latenitefilms/BRAWToolbox/assets/170032222/3fa3d7a1-2a52-4997-9b0b-801ea250b148)

![Screenshot 2024-05-16 at 11 37 46 AM](https://github.com/latenitefilms/BRAWToolbox/assets/170032222/15853aae-7b51-410d-bc9f-8c946f8bb8f4)

<img width="303" alt="Screenshot 2024-05-16 at 11 51 43 AM" src="https://github.com/latenitefilms/BRAWToolbox/assets/170032222/da4dfaa9-6b33-46b6-a59d-a394d5c30354">

**Comment by latenitefilms** [comment]
Sorry for the delayed reply, and sorry you're running into issues!

I assume you've installed the Motion Template, etc?

See: https://brawtoolbox.io/installation/

If you haven't already, can you try granting sandbox access to the drive which contains your BRAW files, restart your computer, and see if that helps?

See: https://brawtoolbox.io/collaboration/

If you're still having issues, can you please send across any crash logs and log files?

See: https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by latenitefilms** [comment]
Closing this issue for now, feel free to re-open if you're still having issues.
