### ISSUE TITLE
Can't import anything

### ISSUE THREAD

**Issue by EytschPi** [latenitefilms/BRAWToolbox#176]
Hi,
I am trying to import 6K files into Final Cut and ayntime I drag anything to a library it makes an event, but then I get some XML error code.  (I'd show you a pic, but it is in german).
At this stage I can't really do anything, so I will need some assistance please.

Cheers, Henning

**Comment by latenitefilms** [comment]
It sounds like you don't have the Motion Template installed?

See:

https://brawtoolbox.io/installation/

**Comment by EytschPi** [comment]
Thank you Chris,

I got it this far now and have the motion templates installed.

The BRAW files (6K) are playing back in Final Cut with… hmm… I guess… framerate issues.

Everything is on 25p, so that shouldn’t be the issue.

I exported the file to ProRes and that plays fine.

I can’t image that it is a processing issue because I have the highest spec’d Mac you can get and it eats video files for breakfast.
The file plays back as if there are some dropped frames or something like that.

I moved the file from the CFast card to my editing drive (2.8GB/sec) since it doesn’t seem to actually get imported into Final Cut, but that didn’t solve anything.

Any idea that this could be?

At the moment this is not a workflow that actually works.

Henning



￼
￼

Henning Pauly
HP42
0160 / 8068 404
YouTube: https://www.youtube.com/user/EytschPi42

 <http://www.facebook.com/henning.pauly>






 <http://maps.google.com/?q=Laimbacherweg+4,+35781+Weilburg>

**Comment by latenitefilms** [comment]
What decode quality are you using? You may have to use a lower quality decode quality for editing, then force it to full quality for export? 

See: https://brawtoolbox.io/workflow-extension/#inspector

You can also see if the "Better Performance" option in the Final Cut Pro Viewer helps?

**Comment by latenitefilms** [comment]
Closing this issue for now, feel free to re-open if you're still having issues.
