### ISSUE TITLE
No BRAW File Selected -- can't edit any raw parameters

### ISSUE THREAD

**Issue by jbrophy94** [latenitefilms/BRAWToolbox#178]
Any time I try to use the BRAW effect on a BRAW clip I imported using the toolbox, I just get a red screen that says No BRAW File Selected. This happens regardless of whether I double click the effect or drag it onto my clip. It is effectively rendering the plugin useless for me because I like to edit the raw data after import. Please help

**Comment by jbrophy94** [comment]
I got it working by selecting the clip in the actual effect window after I already dragged it onto the clip. Is this how it is supposed to work? Thanks very much!

**Comment by latenitefilms** [comment]
The BRAW Toolbox effect is applied WITHIN the Synchronised Clip (inside the Multicam Clip if you're creating Multicam Clips). You should never have to manually apply the BRAW Toolbox effect.

See:

https://brawtoolbox.io/how-to-use/

**Comment by jbrophy94** [comment]
Ok, thank you so much. Sorry for the misunderstanding. I appreciate it!
