### ISSUE TITLE
No B raw file selected when applying effect after import

### ISSUE THREAD

**Issue by urdadsbuddy** [latenitefilms/BRAWToolbox#181]
I imported a bunch of footage and started editing, now attempting to access metadata settings, I apply the Braw toolbox effect ( not sure why this isn't pre applied to the clip after import?) and recieve a "no braw file selected" error. I can manually go through and select the braw clip however this is extremely tedious, and when I do so, it replaces with a section of the clip equivalent in length but at a different start/end point in the clip. The new part of the clip ending where the old part of the clip  (that I want to use) started.

screen recording of problem: https://youtu.be/6nUyfhLjKi0

Thanks

**Comment by latenitefilms** [comment]
You should NEVER manually apply the BRAW Toolbox effect.

It's applied INSIDE the Sync Clip.

See:

https://brawtoolbox.io/how-to-use/
