### ISSUE TITLE
Davinci Resolve not linking BRAW Files from FCPXML

### ISSUE THREAD

**Issue by brendenmasar** [latenitefilms/BRAWToolbox#184]
I bought BRAW Toolbox this morning because my old workflow had an issue that no one could help me solve. But now I have a new one.

I imported my BRAW clips into FCPX using Toolkit and made my edit and exported an FCPXML (1.10). However when I imported the XML into DR for color it isn't linking my files. I get this error: "The clip "A074_08250956_C044" failed to link because the timecode extents do not match any clip in the Media Pool." and none of my clips relinked.

Can anyone help me?

**Comment by latenitefilms** [comment]
Did you use the **Convert PROJECT to Resolve Friendly FCPXML** workflow as described below?

https://brawtoolbox.io/toolbox/#convert-project-to-resolve-friendly-fcpxml

**Comment by brendenmasar** [comment]
Okay thanks for that. As I said, first day so I'm just getting used to it.

However, I imported that FCPXML into DR without anymore issues and made my color corrections, but when I try to import the XML with corrected MOVs from DR back into FCP for finishing, I get this error: 

**The XML document sent from application “Final Cut Pro” could not be imported.** 

The media could not be imported. (The original media on asset with id r29: /fcpxml[1]/resources[1]/asset[28].)

Inappropriate file type or format

**Comment by latenitefilms** [comment]
Normally you would render out a new FCPXML from DaVinci Resolve pointing to your rendered material - at this point, BRAW Toolbox isn't involved at all - you would just be pointing to rendered ProRes files (or similar).

**Comment by brendenmasar** [comment]
Yeah that's what I'm trying to do but that's the error I get. Would there be a work-around using Toolkit?

**Comment by latenitefilms** [comment]
At this point, I believe this would be more a Resolve issue than a BRAW Toolbox issue - as there should be no BRAW files involved, as you're just dealing with rendered ProRes files.

Can you try copy and pasting everything into a new Resolve timeline, and try removing any unneeded/unnecessary effects?

Have you checked the FCPXML in a text editor to make sure it's actually pointing to your rendered files?

Feel free to also share the FCPXML here?
