### ISSUE TITLE
how to modify the XML

### ISSUE THREAD

**Issue by donpingon** [latenitefilms/BRAWToolbox#185]
<img width="403" alt="Screenshot 2024-09-24 at 12 03 37" src="https://github.com/user-attachments/assets/0a5c044e-40e4-4bfc-b5f6-002a00dc5b82">

im getting this message when i import a file onto my final cut pro ,i dont know how to fix it, please see attachement

**Comment by latenitefilms** [comment]
This means the Motion Template is not installed.

See:

https://brawtoolbox.io/troubleshooting/#the-effect-id-is-invalid

Did you install everything as per these instructions?

https://brawtoolbox.io/installation/

**Comment by donpingon** [comment]
i will follow the links provided , hopefully it works

**Comment by donpingon** [comment]
problem solved...thank you
