### ISSUE TITLE
ProApps Folder Issue

### ISSUE THREAD

**Issue by mnemeth-1** [latenitefilms/BRAWToolbox#186]
I just bought BRAW Toolbox so I can edit on Final Cut with my Blackmagic camera, and downloaded the app. It won't let me install the metadata view or LUT's into the ProApps folder on my computer. The only ProApps folder I can find is in Library then Application Support then ProApps Folder. But this does not work. What should I do?

**Comment by latenitefilms** [comment]
Sorry you're having issues!

Can you please share your log files as explained here?

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by mnemeth-1** [comment]
I shared the files like you suggested and haven't heard back. I just want to make sure I did what was needed. Thank you for your help. From what I can tell, I can still work with BRAW files as of now even without the metadata or LUT things installed.

**Comment by latenitefilms** [comment]
Apologies for the delayed reply - funnily enough someone else had this issue, and I thought I was replying to you via email!

It looks like you selected `/Volumes/Nemeth Drive 2/BRAW Toolbox`, whereas you should have selected `/Users/mnemeth/Movies`.

Please quit Final Cut Pro and BRAW Toolbox, and enter this in Terminal:

```
/usr/bin/defaults delete com.latenitefilms.BRAWToolbox
```

If Terminal is too scary, you can also do it manually via these instructions:

https://brawtoolbox.io/troubleshooting/#failed-to-install-motion-template-metadata-view-or-luts

Then try install the Motion Templates again, making sure you use their default paths as explained here:

https://brawtoolbox.io/installation/

And yes, BRAW Toolbox will still work without the LUTs and Metadata. The LUTs are only used for HDR workflows, and the Custom Metadata View is just an extra Metadata View for the Info Inspector - it doesn't affect BRAW playback.

Hope this helps!
