### ISSUE TITLE
Poor playback quality even in "full" or "Automatic (ultra HD)".

### ISSUE THREAD

**Issue by JeanSemeur** [latenitefilms/BRAWToolbox#188]
![FCP BRAW TOOLBOX](https://github.com/user-attachments/assets/7c1c33d8-0a96-4fb3-8306-4f2ba9f30ce2)
![RESOLVE](https://github.com/user-attachments/assets/dee4bb31-58e2-494f-ad63-33f745ce3f6f)
Hello Chris,
I purchased Braw Toolbox today to make a short video tutorial for my PDF readers.
I'm amazed at the poor quality in playback but when you choose “full” or “Automatic (ultra HD)”. I compared it to the same file in Resolve and it's much better.
Have I done something wrong?
(MacBook Pro M2 Pro - Ventura 13.6.9- FCP 10.8.1)
My Braw shots are shot in Q0 from a 4K bmpcc.
Thanks Chris for your feedback. And let me know if you need more precision to make a diagnosis.
Martin Gosset
![INSPECTOR SETTINGS](https://github.com/user-attachments/assets/87814dd9-c090-4abd-9728-92842ac9e30e)

Translated with DeepL.com (free version)

**Comment by JeanSemeur** [comment]
Sorry, the problem came from global settings.
But not sure to understand very well the différence between decode setting and global setting.
Martin

**Comment by latenitefilms** [comment]
Sorry for the very delayed reply - I've been travelling.

Have you got `Better Quality` or `Better Performance` selected in Final Cut Pro's Viewer?

<img width="392" alt="image" src="https://github.com/user-attachments/assets/878c7f1b-3b74-43e7-b583-45d817fd7cd0">

**Comment by latenitefilms** [comment]
Decode quality is explained in more detail here:

https://brawtoolbox.io/workflow-extension/#inspector
