### ISSUE TITLE
Remove single BRAW clip from ingest list

### ISSUE THREAD

**Issue by TheDaveChap** [latenitefilms/BRAWToolbox#19]
There doesn't seem to be a way to remove a single cli (or selected clips) from the list before ingesting/processing. You can clear all the files, but if you add a file by accident in a list of others, you can't remove it and you have to clear the list and select the correct ones. It would be great if the delete key would remove any selected clips from the list, or if there was a button below to "Clear Selected Clips" that became available when you selected clips in the list.

**Comment by TheDaveChap** [comment]
I have quite a few interviews shot in BRAW with 2 cameras, and the Finder was taking a bit to show the preview, so I decided to select all 8 clips and use BRAW Toolbox to navigate them and remove the 1 interview I had already imported. I realized that didn't work.

**Comment by latenitefilms** [comment]
Agreed - will try add in the next public beta.

**Comment by latenitefilms** [comment]
This will be included in next beta.
