### ISSUE TITLE
Misaligned "Reset Metadata" Button in 1.0.0 (16) 

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/BRAWToolbox#20]
All previous mentioned problems fix, THANK YOU!

One small bug, the "Reset Metadata" button is misplaced and can be cut off when resizing the inspector window. nSee attached screenshot.
<img width="386" alt="Screen Shot 2023-01-05 at 12 52 16 PM" src="https://user-images.githubusercontent.com/72329359/210847726-a15d6bc1-cf05-4841-9a8f-575fb1e3a839.png">

Also a question on a separate topic, what is the proper workflow if I want work in HDR in FCP? Is that supported?

**Comment by latenitefilms** [comment]
To be honest - I have no idea why this happens. All three buttons are completely the same. I can only assume it's some kind of bug/quirk in Final Cut Pro. I have asked the Final Cut Pro team about this, but they didn't have any ideas.

**Comment by JW144754** [comment]
Can confirm that it is inconsistent, that I cannot reproduce the problem all the time. It is currently aligned correctly most of the time.

**Comment by latenitefilms** [comment]
I've come up with a compromise that's ok. Will include in next beta.
