### ISSUE TITLE
Select next clip when removing a clip in Workflow Extension

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/BRAWToolbox#38]
If you remove a clip from the toolbox, could the next clip be automatically selected, the way the Finder works?

_Originally posted by @tomwolsky in https://github.com/latenitefilms/BRAWToolbox/discussions/31#discussioncomment-4779183_

**Comment by tomwolsky** [comment]
Thank you Chris.

**Comment by latenitefilms** [comment]
This will be fixed in 1.0.1.
