### ISSUE TITLE
Add progress bar to "Prepare BRAW Files"

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/BRAWToolbox#5]
@tangierc writes:

> One potential enhancement could be to have a status bar or some other visual to represent the "Prepare BRAW Files" process. I only knew that activity was happening by watching the lights flashing on my RAID and hearing the drives working.

**Comment by TheDaveChap** [comment]
Thought the same thing! Would help a ton.

**Comment by latenitefilms** [comment]
This will be added in next public beta, thanks!
