### ISSUE TITLE
Splited clip issue

### ISSUE THREAD

**Issue by rakeshdevan** [latenitefilms/BRAWToolbox#54]
After importing to the timeline, when I blade the clip into 2, the 2nd clip is the same as the 1st clip. It's not the continuation of the video. Why? Extended video selected for Gamma for generating. 

https://user-images.githubusercontent.com/124019045/215661840-7ae8d5eb-1c9a-43c1-b6e2-d44d7b8e54e9.mp4

**Comment by latenitefilms** [comment]
You shouldn't edit the "insides" of the Synchronised Clip - you should insert the Synchronised Clip (or Multicam) in your timeline and edit it there.

**Comment by rakeshdevan** [comment]
How do you bring it into the timeline?  I just double-click on the Synchronised
Clip and audio & video came in the timeline. Is there any other way to
bring the clips to the timeline?

Thanks,

Rakesh.

**Comment by latenitefilms** [comment]
The same way you'd bring in any Synchronised Clip or Multicam Clip into your Project/Timeline. 

You can drag the Synchronised Clip or Multicam Clip from the Browser into your Project/Timeline, or use keyboard shortcuts like Q, W or E.

There's some videos here demonstrating: 

https://brawtoolbox.io/videos/
