### ISSUE TITLE
The Effect ID is Invalid - FxPlug4 not installing correctly

### ISSUE THREAD

**Issue by Rattie666** [latenitefilms/BRAWToolbox#55]
Getting the above warning and Black files.  I worked through the recommended steep to fix it, but still no better.
<img width="1768" alt="Screenshot 2023-01-31 at 13 54 15" src="https://user-images.githubusercontent.com/124064498/215789735-d1eb96be-380f-4946-bc97-f69b0586d8d7.png">

**Comment by latenitefilms** [comment]
For some reason Final Cut Pro is not loading the FxPlug4 correctly.

See: https://brawtoolbox.io/troubleshooting/#the-effect-id-is-invalid

**Comment by Rattie666** [comment]
Thanks for the reply. 

As I said in my original email I did the three steps in the link you kindly sent.  I did this before contacting you.

Ian

**Comment by latenitefilms** [comment]
Ummm, that's very odd. This is the first time we've had a case where trashing FCPX's preferences or just reinstalling FCPX didn't kick it back into gear. I assume you've tried just restarting your whole computer?

What version of macOS? What version of Final Cut Pro? What type of Mac?

I assume BRAW Toolbox is just in your `/Applications` folder, and you haven't renamed it or anything?

Are you able to type the below into the macOS `Terminal` application, and take a screenshot of what it returns?

```
pluginkit -mv -p FxPlug | grep "BRAW"
```

As long as the BRAW Toolbox application is in your Applications folder, macOS should automagically detect the FxPlug4 plugin and "install" it within Apple Motion (which then gets used by Final Cut Pro).

**Comment by Rattie666** [comment]
￼

From Terminal

Last login: Wed Feb  1 08:04:17 on console
***@***.*** ~ % pluginkit -mv -p FxPlug | grep "BRAW"
     com.latenitefilms.BRAWToolbox.Renderer(1.1)	24E392EF-9557-44F8-B5B0-CF4E88B34195	2023-01-31 08:40:58 +0000	/Applications/BRAW Toolbox.app/Contents/PlugIns/BRAW Toolbox Renderer.pluginkit
***@***.*** ~ %

**Comment by latenitefilms** [comment]
It looks like macOS is detecting the FxPlug4 effect fine.

Do you see the BRAW Toolbox effect in your Effects Browser in Final Cut Pro?

I assume you installed the Motion Templates, Metadata View and LUTs ok?

https://brawtoolbox.io/installation/

If things are still not working, can you send me the log files here:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by Rattie666** [comment]
> 
> It looks like macOS is detecting the FxPlug4 effect fine.
> 
> Do you see the BRAW Toolbox effect in your Effects Browser in Final Cut Pro?
> 
Yes I can see
> I assume you installed the Motion Templates, Metadata View and LUTs ok?
> 
> https://brawtoolbox.io/installation/
> 
Yes all OK.  I even uninstalled and then reinstalled.  No difference
> If things are still not working, can you send me the log files here:
> 
> https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files
> 
Not sure how to do this.  Tried and it did work

**Comment by latenitefilms** [comment]
Very strange. You're definitely getting the same error when you drag the green icon to your library still?

If you apply a BRAW Toolbox effect to an existing clip or a generator, and manually select a BRAW file using the Inspector, does it work?

Are you able to share a screen recording of everything? Alternatively I can try jump on a screen sharing session with you tomorrow to try and solve? I'm in a Melbourne, Australia timezone.

**Comment by Rattie666** [comment]
> Very strange. You're definitely getting the same error when you drag the green icon to your library still?
> 

Yes still getting the same issue.
> If you apply a BRAW Toolbox effect to an existing clip or a generator, and manually select a BRAW file using the Inspector, does it work?
> 
> Are you able to share a screen recording of everything? Alternatively I can try jump on a screen sharing session with you tomorrow to try and solve? I'm in a Melbourne, Australia timezone.
> 
 I will send you a screen recording in time for your morning.

Ian

**Comment by latenitefilms** [comment]
Just checking in @Rattie666 - are you still having issues? I don't think I've received your screen recording yet? When you upload it, please make a note that it's from Rattie666, so I know. Thanks!

**Comment by Rattie666** [comment]
Thanks for getting in touch.

Yes I am, but I got a job to do some interviews when someone dropped out at short notice, the joys of freelancing. I will be done later today’s so will get back to this on Monday.

Ian.

**Comment by Rattie666** [comment]
I couldn't get the file size down to a size that this link will accept so sent by Filemail separately.

**Comment by latenitefilms** [comment]
You can upload to the link at the bottom of this page:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by Rattie666** [comment]
Chris,

Fell down at the first hurdle.  No link to library.
￼
I'm presuming it is this library
￼

If so there is no groups containers within
￼

I did find the Diagnostic Reports though.  There were no BRAWToolbox crash reports

Ian

**Comment by Rattie666** [comment]
Chris, 

Just to let you know that on the off chance that it might work I uninstalled your program, rebooted my Mac and then reinstalled the App. The good news is that it is now working. 

No idea why it wouldn't work the first time round or second time come to that, but it’s third time lucky. 

I appreciate the time you spent on this and good luck with your program, It will make my life easier. I'm quite happy working in resolve but Final Cut is just so much quicker and easier to use.

Thank you.

Ian.

**Comment by latenitefilms** [comment]
Great news! Thanks Ian!

Happy cutting!
