### ISSUE TITLE
Motion Template Plugin Missing

### ISSUE THREAD

**Issue by rheacom** [latenitefilms/BRAWToolbox#66]
The file import appears successful, yet I keep seeing this.
<img width="1361" alt="Screenshot 2023-02-02 at 2 04 09 PM" src="https://user-images.githubusercontent.com/124312479/216459950-9ad45865-8283-42a7-ae4b-ad5c2f2526d6.png">

**Comment by rheacom** [comment]
I'm on a deadline - any help appreciated.
brian@storieswelltold.com

**Comment by latenitefilms** [comment]
Have you installed the Motion Template correctly?

https://brawtoolbox.io/installation/

Do you see the BRAW Toolbox in your list of Effects?

**Comment by latenitefilms** [comment]
To answer your specific question, yes, BRAW Toolbox works great with Ventura, however FYI, the latest Ventura update doesn't play nicely with Final Cut Pro with a large amount of clips. See:

https://github.com/CommandPost/FinalCutPro/issues/86

This is unrelated to BRAW Toolbox.

**Comment by latenitefilms** [comment]
Just checking in @rheacom - were you able to solve this?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, however feel free to add a comment or re-open if you're still having problems.
