### ISSUE TITLE
Can't set in and out points or put a cut on the timeline

### ISSUE THREAD

**Issue by Wilsonjr2001** [latenitefilms/BRAWToolbox#69]
So I'm having the issue where if I set a in and out point it will just set it to the start of the clip and if I put a cut on the timeline it will reset the cut clip to the start of the clip. Is there anything I'm doing wrong or is it a bug that can be fixed?

Thank you in advance!
Love the plugin !

**Comment by latenitefilms** [comment]
It sounds like you're editing the "insides" of a Synchronised Clip or Multicam Clip?

You shouldn't "cut" the Generator that lives inside the Synchronised Clip or Multicam Clip - however you are able to adjust the RAW parameters that exist on the Generator as an Effect.

You should insert the Synchronised Clip or Multicam Clip onto a Project/Timeline - and edit there.

See: https://brawtoolbox.io/installation/
