### ISSUE TITLE
Braw Toolbox does not appear in the inspector

### ISSUE THREAD

**Issue by Lamogen** [latenitefilms/BRAWToolbox#73]
![Screenshot 2023-02-07 at 1 53 30 AM](https://user-images.githubusercontent.com/124639324/217113368-2e7d5983-a9fb-47b9-857d-b81e67158b98.png)

**Comment by latenitefilms** [comment]
The BRAW Toolbox effect is applied WITHIN the Synchronised Clip. 

If you create Multicam Clips from BRAW Toolbox, then you'll need to open the Multicam Clip, then open the first angle, which is a Synchronised Clip, to access the BRAW Toolbox controls.

See: https://brawtoolbox.io/installation/#instructions
