### ISSUE TITLE
The Effect ID is Invalid - FxPlug4 not installing correctly

### ISSUE THREAD

**Issue by lizzyblu03** [latenitefilms/BRAWToolbox#77]
Hi, trying to fig out why I'm not seeing vid, only sound file. I drag the green icon into library and then it says ""The effect ID is invalid". I continue, and I only get sound file in my Final Cut Pro event. Please help.

**Comment by latenitefilms** [comment]
Have you already tried these things?

https://brawtoolbox.io/troubleshooting/#the-effect-id-is-invalid

**Comment by lizzyblu03** [comment]
Hi! Yes, and just tried all again w reset just in case. No luck yet

**Comment by lizzyblu03** [comment]
<img width="433" alt="Screen Shot 2023-02-08 at 7 15 27 PM" src="https://user-images.githubusercontent.com/124851953/217708844-584aa430-5ac3-4be0-9e25-9522337dafe9.png">

**Comment by lizzyblu03** [comment]
screen shot in case that's helpful

**Comment by latenitefilms** [comment]
We've had a couple of users run into similar things, but it always just solves itself. We haven't ever been able to reproduce the issue.

See: #55 and #64

@Rattie666 said:

> Just to let you know that on the off chance that it might work I uninstalled your program, rebooted my Mac and then reinstalled the App. The good news is that it is now working.
> 
> No idea why it wouldn't work the first time round or second time come to that, but it’s third time lucky.

Can you try, uninstall, reboot, and re-install?

Uninstall instructions here: https://brawtoolbox.io/uninstall/

**Comment by Rattie666** [comment]
Chris,

As I was using the App yesterday, something crossed my mind. When reinstalling the toolbox for the third time, I read all the prompts carefully rather than just rushing through them. When I was prompted to do something with the Application Support screen, the App opened the Pro Apps screen requiring me to navigate to Application Support. In a rush to install, perhaps I clicked on what opened rather than the correct thing.

Just a thought.

Ian.

**Comment by latenitefilms** [comment]
In theory, you should just be able to rush through it, as those folder should already exists, and the **Grant Access** file browser should already be pointing to the right place. We improved this in v1.0.1, however, I'd suggest holding off updating to v1.0.1 for now, as it has a bug and we're still waiting on Apple to approve v1.0.2 which fixes it.

**Comment by lizzyblu03** [comment]
I'll give it a go today. Fingers crossed, thankee

**Comment by lizzyblu03** [comment]
Hi, tried the uninstall tool, got an error. So, I deleted the app and reinstalled twice, same protocol, still not working. Ideas?

**Comment by lizzyblu03** [comment]
Hi, uninstalled everything and reinstalled and it works!!
