### ISSUE TITLE
Media preview goes black sometimes?

### ISSUE THREAD

**Issue by JW144754** [latenitefilms/BRAWToolbox#8]
I have not quite found out the cause yet, but the preview window, as well the timeline preview goes black sometimes? In the screen recording attached it is showing black, but in a previous test it was fine. Relaunching FCP, refresh metadata does not help either.

https://user-images.githubusercontent.com/72329359/209753750-7866517a-ba80-4f8a-8230-c81965a4c99f.mp4

**Comment by latenitefilms** [comment]
I'm not entirely sure what's causing this. Final Cut Pro uses seperate processes for generating thumbnails, so I'm assuming that something is preventing it from updating the thumbnails - even though it looks like it's still able to play back the synchronised clip fine.

I'm currently working on some big re-writes/changes for the next public beta, and HOPEFULLY this issue will be resolved as part of those changes.

**Comment by JW144754** [comment]
Sounds good, look forward to it! This is another game changing plugin. Would have saved me hundreds of hours of transcoding with DaVinci.

**Comment by latenitefilms** [comment]
Curious... are you ever running the BRAW Toolbox app, or did you just run it once then quit and never open it again?

**Comment by JW144754** [comment]
If you are referring to the initial installer that says "give permission to these two folder, then you can close this application" then yes, I just installed the Motion template and the plugin and closed it. I will keep testing it tomorrow. Other side of earth here, goodnight!

**Comment by latenitefilms** [comment]
I'm HOPING this should be resolved in the next beta, and if not, we'll be able to get some error messages as to what's happening, so I'm going to close this issue for now and we can revisit once the next beta is out and tested.
