### ISSUE TITLE
High Fram Rate Clips are Getting Cut Off

### ISSUE THREAD

**Issue by CodyCarlson22** [latenitefilms/BRAWToolbox#87]
When I import high frame rate (shot in 59.94fps and played back in 23.98fps) clips I see the entire clip when I import into Davinci Resolve, but in FCPX the last 7 seconds get cut off. Do you have any suggestions to remedy this?

**Comment by latenitefilms** [comment]
That's strange. Are you able to send me one of those clips so that I can try and reproduce?

You can upload here:

https://latenitefilms.digitalpigeon.com

**Comment by latenitefilms** [comment]
Is the duration correct, and do you see the whole file in the Workflow Extension prior to importing into Final Cut Pro? Is it a spanned clip (ie across two BRAW files)?

**Comment by latenitefilms** [comment]
I haven't had any further response, so I'm going to close this issue for now. Feel free to re-open if you still need help!
