### ISSUE TITLE
Add ability to resize Workflow Extension Viewer

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/BRAWToolbox#9]
> If you resize the Workflow Extension, the Viewer will get bigger too.
> I am not sure if I am doing this wrong again, but mine is not doing that. The bottom part get bigger, but not the viewer. I do > not believe there is anywhere for me to drag to resize the viewer either?

https://user-images.githubusercontent.com/72329359/209979081-4570adb9-d00c-471f-a5ac-99fcdd89f068.mov

_Originally posted by @JW144754 in https://github.com/latenitefilms/BRAWToolbox/issues/6#issuecomment-1367433510_

**Comment by latenitefilms** [comment]
I totally agree. The main thing holding this back is that Interview Builder in Xcode is the devil, so this is way more tricky than you'd think. I'll try solve at some point.

**Comment by JW144754** [comment]
Haha I had a feeling it's more difficult than it seems. It's just a logical/practical thing to have. Don't lose sleep over it!

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22286696/210123618-7968ae44-e9e7-4dfc-b0c3-b23b942b84a2.png">

**Comment by JW144754** [comment]
You rock! Happy New Year!
