### ISSUE TITLE
How to add Stabilization with Plugin?

### ISSUE THREAD

**Issue by Wilsonjr2001** [latenitefilms/BRAWToolbox#90]
So I love the plugin but can't use the built in stabilization of Final Cut and I downloaded Gyroflow tool but it doesn't work like just shoots an error. What should I do? 

Thank you in advance!!!

**Comment by latenitefilms** [comment]
Unfortunately Final Cut Pro doesn't allow you to currently stabilise Multicam Clips or Synchronised Clips.

If you want to use FCPX's built-in stabiliser, you'll need to export that section of the clip as a ProRes and bring it back it. Obviously all your RAW attributes will be baked in.

Gyroflow Toolbox will work with any BRAW cameras that have built-in stabilisation such as the Pocket Cinema Camera 4K/6K.

Alternatively, you could use a third party tool like [Lock & Load X](https://coremelt.com/products/lock-and-load-x).
