### ISSUE TITLE
Unable to access a document in the App Group Folder

### ISSUE THREAD

**Issue by robchinn** [latenitefilms/BRAWToolbox#92]
Opened FCPX to try BRAW Toolbox for first time. Opened it from the Extension button. Selected a BRAW clip from a Pocket 4K camera to import. I immediately received the following error (screenshot attached): A fatal error has occurred. BRAW Toolbox was unable to access a document in the App Group folder. Please contact the developer for assistance.

<img width="287" alt="Screenshot 2023-02-27 at 9 50 38 PM" src="https://user-images.githubusercontent.com/126538598/221744897-e1ab5ccc-76eb-4d55-9260-a450d0671ac9.png">

I'm running FCPX 10.6.5, BRAW Toolbox v1.0.4 (38), Blackmagic RAW SDK v2.8, Mac OS 13.0.1 on  Mac Studio M1 Max.

**Comment by latenitefilms** [comment]
Did you install the Motion Template, etc. prior to launching Final Cut Pro?

See: https://brawtoolbox.io/installation/

**Comment by robchinn** [comment]
Nope - I didn't read the instructions. Sorry. Working now.
