### ISSUE TITLE
The Effect ID is Invalid - FxPlug4 not installing correctly

### ISSUE THREAD

**Issue by NYSMuseum** [latenitefilms/BRAWToolbox#94]
Trying to import BRAW to FCPX.  FCPX gives this error upon dragging button into FCP library. I cannot see the video in FCP, only see audio.

**Comment by latenitefilms** [comment]
That error basically means that for some reason the BRAW Toolbox effect hasn't been installed in Final Cut Pro correctly.

Try the steps listed here: https://brawtoolbox.io/troubleshooting/#the-effect-id-is-invalid

**Comment by NYSMuseum** [comment]
I followed the directions in troubleshooting. Still having the issue.  One thing I'm noticing is that the "install motion templates" button does not grey out like the others.

**Comment by NYSMuseum** [comment]
I do see this response in terminal: 

com.latenitefilms.BRAWToolbox.Renderer(1.1)	12D6638F-A4AC-45E9-A21C-C9BBF70E4CF8	2023-03-02 02:37:44 +0000	/Applications/BRAW Toolbox.app/Contents/PlugIns/BRAW Toolbox Renderer.pluginkit

**Comment by NYSMuseum** [comment]
There aren't any new folders or braw references in the motion templates folder

**Comment by latenitefilms** [comment]
I assume you're using latest v1.0.5 release from the Mac App Store?

Did you try running the Uninstall Tool?

https://brawtoolbox.io/uninstall/

Try uninstalling then follow these installations:

https://brawtoolbox.io/installation/

**Comment by NYSMuseum** [comment]
That worked!
